const library = [
				{
            		roName: "E-Pick",
            		type: "accessory",
            		manufacturer:"Robotiq",
            		payloadMin: 10,
            		payloadMax: 10,
            		weightMin: 0,
            		weightMax: 0,
            		reachMin: 0,
            		reachMax: 0,
            		repeatMin: 0,
            		repeatMax: 0,
            		axes: "",
            		image:"./Robot_Images/epick.png"
            		
                },
            	{
            		roName: "VS-6556",
            		type: "robot",
            		manufacturer:"Denso",
            		payloadMin: 7,
            		payloadMax: 7,
            		weightMin: 35,
            		weightMax: 35,
            		reachMin: 653,
            		reachMax: 653,
            		repeatMin: 0.020,
            		repeatMax: 0.020,
            		axes: "6",
            		image:"./Robot_Images/VS6556.png"
            		
                },
            	{
            		roName: "VP-060",
            		type: "robot",
            		manufacturer:"Denso",
            		payloadMin: 4,
            		payloadMax: 4,
            		weightMin: 28,
            		weightMax: 28,
            		reachMin: 605,
            		reachMax: 605,
            		repeatMin: 0.020,
            		repeatMax: 0.020,
            		axes: "6",
            		image:"./Robot_Images/VS060.jpg"
            		
                },
            	{
            		roName: "VP-050",
            		type: "robot",
            		manufacturer:"Denso",
            		payloadMin: 4,
            		payloadMax: 4,
            		weightMin: 27,
            		weightMax: 27,
            		reachMin: 505,
            		reachMax: 505,
            		repeatMin: 0.020,
            		repeatMax: 0.020,
            		axes: "6",
            		image:"./Robot_Images/VS060.jpg"
            		
                },
                {
            		roName: "TX2-90",
            		type: "robot",
            		manufacturer:"Staubli",
            		payloadMin: 9,
            		payloadMax: 9,
            		weightMin: 114,
            		weightMax: 114,
            		reachMin: 1000,
            		reachMax: 1000,
            		repeatMin: 0.030,
            		repeatMax: 0.030,
            		axes: "6",
            		image:"./Robot_Images/Tx290.jpg"
                },
            	{
            		roName: "TX2-60",
            		type: "robot",
            		manufacturer:"Staubli",
            		payloadMin: 5,
            		payloadMax: 5,
            		weightMin: 52,
            		weightMax: 52,
            		reachMin: 670,
            		reachMax: 670,
            		repeatMin: 0.020,
            		repeatMax: 0.020,
            		axes: "6",
            		image:"./Robot_Images/TX260.png"
                },
            	{
            		roName: "TX2-40",
            		type: "robot",
            		manufacturer:"Staubli",
            		payloadMin: 2.3,
            		payloadMax: 2.3,
            		weightMin: 29,
            		weightMax: 29,
            		reachMin: 515,
            		reachMax: 515,
            		repeatMin: 0.020,
            		repeatMax: 0.020,
            		axes: "6",
            		image:"./Robot_Images/Tx240.jpg"
            		
                },
            	{
            		roName: "VP-5243",
            		type: "robot",
            		manufacturer:"Denso",
            		payloadMin: 3,
            		payloadMax: 3,
            		weightMin: 13,
            		weightMax: 13,
            		reachMin: 430,
            		reachMax: 430,
            		repeatMin: 0.020,
            		repeatMax: 0.020,
            		axes: "5",
            		image:"./Robot_Images/6242.jpeg"
            		
                },
            	{
            		roName: "VP-6242",
            		type: "robot",
            		manufacturer:"Denso",
            		payloadMin: 2.5,
            		payloadMax: 2.5,
            		weightMin: 15,
            		weightMax: 15,
            		reachMin: 432,
            		reachMax: 432,
            		repeatMin: 0.020,
            		repeatMax: 0.020,
            		axes: "6",
            		image:"./Robot_Images/6242.jpeg"
            		
                },
            	{
            		roName: "Cobotta",
            		type: "robot",
            		manufacturer:"Denso",
            		payloadMin: 0.5,
            		payloadMax: 0.5,
            		weightMin: 4,
            		weightMax: 4,
            		reachMin: 342.5,
            		reachMax: 342.5,
            		repeatMin: 0.500,
            		repeatMax: 0.500,
            		axes: "6",
            		image:"./Robot_Images/cobotta.jpg"
            		
                },
            	{
            		roName: "KR10R11002",
            		type: "robot",
            		manufacturer:"Kuka",
            		payloadMin: 11.1,
            		payloadMax: 11.1,
            		weightMin: 55,
            		weightMax: 55,
            		reachMin: 1101,
            		reachMax: 1101,
            		repeatMin: 0.020,
            		repeatMax: 0.020,
            		axes: "6",
            		image:"./Robot_Images/kr6.jpg"
            		
                },
            	{
            		roName: "KR6R7002",
            		type: "robot",
            		manufacturer:"Kuka",
            		payloadMin: 6,
            		payloadMax: 6,
            		weightMin: 53,
            		weightMax: 53,
            		reachMin: 726,
            		reachMax: 726,
            		repeatMin: 0.020,
            		repeatMax: 0.020,
            		axes: "6",
            		image:"./Robot_Images/kr6r700.jpg"
            		
                },
            	{
            		roName: "KR3R540",
            		type: "robot",
            		manufacturer:"Kuka",
            		payloadMin: 3,
            		payloadMax: 3,
            		weightMin: 26,
            		weightMax: 26,
            		reachMin: 541,
            		reachMax: 541,
            		repeatMin: 0.020,
            		repeatMax: 0.020,
            		axes: "6",
            		image:"./Robot_Images/KR-3-R540.jpg"
            		
                },
                {
            		roName: "UR16 e-Series",
            		type: "robot",
            		manufacturer:"Universal Robots",
            		payloadMin: 16,
            		payloadMax: 16,
            		weightMin: 33,
            		weightMax: 33,
            		reachMin: 900,
            		reachMax: 900,
            		repeatMin: 0.050,
            		repeatMax: 0.050,
            		axes: "6",
            		image:"./Robot_Images/UR16e.png"
            		
                },
                {
            		roName: "UR3 CB-Series",
            		type: "robot",
            		manufacturer:"Universal Robots",
            		payloadMin: 3,
            		payloadMax: 3,
            		weightMin: 11,
            		weightMax: 11,
            		reachMin: 500,
            		reachMax: 500,
            		repeatMin: 0.100,
            		repeatMax: 0.100,
            		axes: "6",
            		image:"./Robot_Images/ur3-cb.png"
            		
                },
                {
            		roName: "UR3 e-Series",
            		type: "robot",
            		manufacturer:"Universal Robots",
            		payloadMin: 3,
            		payloadMax: 3,
            		weightMin: 11,
            		weightMax: 11,
            		reachMin: 500,
            		reachMax: 500,
            		repeatMin: 0.030,
            		repeatMax: 0.030,
            		axes: "6",
            		image:"./Robot_Images/ur3e.jpg"
                },
            	{
            		roName: "Inspector P64X",
            		type: "accessory",
            		manufacturer:"SICK",
            		payloadMin: 0,
            		payloadMax:0 ,
            		weightMin: 0,
            		weightMax: 0,
            		reachMin: 0,
            		reachMax: 0,
            		repeatMin:0 ,
            		repeatMax: 0,
            		axes:"" ,
            		image:"./Robot_Images/s300.png"
                },
            	{
            		roName: "FT300",
            		type: "accessory",
            		manufacturer:"Robotiq",
            		payloadMin: 0,
            		payloadMax:0 ,
            		weightMin: 0,
            		weightMax: 0,
            		reachMin: 0,
            		reachMax: 0,
            		repeatMin:0 ,
            		repeatMax: 0,
            		axes:"" ,
            		image:"./Robot_Images/FT300.jpeg"
                },
            	{
            		roName: "R2000iA",
            		type: "robot",
            		manufacturer:"Fanuc",
            		payloadMin: 165,
            		payloadMax: 165,
            		weightMin: 1210,
            		weightMax: 1210,
            		reachMin: 2650,
            		reachMax: 2650,
            		repeatMin: 0.200,
            		repeatMax: 0.200,
            		axes: "6",
            		image:"./Robot_Images/2000iA.png"
                },
            	{
            		roName: "M10iA",
            		type: "robot",
            		manufacturer:"Fanuc",
            		payloadMin: 10,
            		payloadMax: 10,
            		weightMin: 130,
            		weightMax: 130,
            		reachMin: 1422,
            		reachMax: 1422,
            		repeatMin: 0.080,
            		repeatMax: 0.080,
            		axes: "6",
            		image:"./Robot_Images/M10.jpg"
                },
            	{
            		roName: "LR MATE 200iD",
            		type: "robot",
            		manufacturer:"Fanuc",
            		payloadMin: 7,
            		payloadMax: 7,
            		weightMin: 25,
            		weightMax: 25,
            		reachMin: 717,
            		reachMax: 717,
            		repeatMin: 0.010,
            		repeatMax: 0.010,
            		axes: "6",
            		image:"./Robot_Images/LRM200iD.jpg"
                },
            	{
            		roName: "IRB1200",
            		type: "robot",
            		manufacturer:"ABB",
            		payloadMin: 7,
            		payloadMax: 7,
            		weightMin: 52,
            		weightMax: 52,
            		reachMin: 700,
            		reachMax: 700,
            		repeatMin: 0.020,
            		repeatMax: 0.020,
            		axes: "6",
            		image:"./Robot_Images/robot.png"
                },
            	{
            		roName: "IRB120",
            		type: "robot",
            		manufacturer:"ABB",
            		payloadMin: 3,
            		payloadMax: 3,
            		weightMin: 25,
            		weightMax: 25,
            		reachMin: 580,
            		reachMax: 580,
            		repeatMin: 0.010,
            		repeatMax: 0.010,
            		axes: "6",
            		image:"./Robot_Images/robot.png"
                },
            	{
            		roName: "IRB1100",
            		type: "robot",
            		manufacturer:"ABB",
            		payloadMin: 4,
            		payloadMax: 4,
            		weightMin: 21,
            		weightMax: 21,
            		reachMin: 580,
            		reachMax: 580,
            		repeatMin: 0.010,
            		repeatMax: 0.010,
            		axes: "6",
            		image:"./Robot_Images/robot.png"
                },
            	{
            		roName: "RX160",
            		type: "robot",
            		manufacturer:"Staubli",
            		payloadMin: 28,
            		payloadMax: 28,
            		weightMin: 248,
            		weightMax: 248,
            		reachMin: 1710,
            		reachMax: 1710,
            		repeatMin: 0.050,
            		repeatMax: 0.050,
            		axes: "6",
            		image:"./Robot_Images/robot.png"
                },
                {
            		roName: "UR5 CB-Series",
            		type: "robot",
            		manufacturer:"Universal Robots",
            		payloadMin: 5,
            		payloadMax: 5,
            		weightMin: 18,
            		weightMax: 18,
            		reachMin: 850,
            		reachMax: 850,
            		repeatMin: 0.100,
            		repeatMax: 0.100,
            		axes: "6",
            		image:"./Robot_Images/UR5e.png"
                },
                {
            		roName: "UR5 e-Series",
            		type: "robot",
            		manufacturer:"Universal Robots",
            		payloadMin: 5,
            		payloadMax: 5,
            		weightMin: 18,
            		weightMax: 18,
            		reachMin: 850,
            		reachMax: 850,
            		repeatMin: 0.030,
            		repeatMax: 0.030,
            		axes: "6",
            		image:"./Robot_Images/UR5e.png"
                },
                {
            		roName: "UR10 CB-Series",
            		type: "robot",
            		manufacturer:"Universal Robots",
            		payloadMin: 10,
            		payloadMax: 10,
            		weightMin: 29,
            		weightMax: 29,
            		reachMin: 1300,
            		reachMax: 1300,
            		repeatMin: 0.100,
            		repeatMax: 0.100,
            		axes: "6",
            		image:"./Robot_Images/UR10e.jpg"
                },
                {
            		roName: "UR10 e-Series",
            		type: "robot",
            		manufacturer:"Universal Robots",
            		payloadMin: 10,
            		payloadMax: 10,
            		weightMin: 29,
            		weightMax: 29,
            		reachMin: 1300,
            		reachMax: 1300,
            		repeatMin: 0.050,
            		repeatMax: 0.050,
            		axes: "6",
            		image:"./Robot_Images/UR10e.jpg"
                }
            	]